In [2]:
import torch

In [5]:
x = torch.empty(5, 3)

In [6]:
print(x)

tensor([[2.3051e-12, 7.1429e+31, 2.5226e-18],
        [1.6898e-04, 1.0015e-11, 7.7196e-10],
        [4.2493e-05, 4.1198e-11, 2.6406e-06],
        [2.9571e-18, 7.2646e+22, 7.2250e+28],
        [2.5226e-18, 2.4283e-18, 7.1061e+31]])


In [7]:
type(x)

torch.Tensor

In [9]:
torch.tensor([10, 8])

tensor([10,  8])

**new_\*** methods can be used to generate a tensor using properties of the input tensor, e.g. dtype.

*dtype* argument set the type of the items inside the tensor.

In [20]:
tensor1 = torch.tensor([6, 3], dtype = torch.double)

tensor([6., 3.], dtype=torch.float64)

In [22]:
tensor2 = tensor1.new_ones(3, 2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

**new_*** methods can also set properties for the tensor, e.g. dtype

**randn_like** method create a tensor with same size as the input tensor.

In [23]:
tensor3 = torch.randn_like(tensor2, dtype = torch.float)

tensor([[ 0.5017,  1.4968],
        [-0.0384, -0.5313],
        [ 1.7145, -1.0336]])

you get the size of a tensor using the method tensor.*size()*

In [54]:
tensor1.size()

torch.Size([2])

In [24]:
tensor3.size() == tensor2.size()

True

### Operations

torch.*add(tensor1, tensor2)* will perform a sum both tensors in the arguments.

In [26]:
torch.add(tensor1, tensor2)

tensor([[7., 4.],
        [7., 4.],
        [7., 4.]], dtype=torch.float64)

tensor.*view(* *args)* method reshape the tensor to match the args, the arguments size must match the tensor size.

In [44]:
tensor2.view(6)

tensor([1., 1., 1., 1., 1., 1.], dtype=torch.float64)

if the tensor have only one element, use tensor.*item()* method to extract the element value

In [57]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1691])
0.16905631124973297


torch.*numel(input)* method returns the total number of elements inside the tensor.

In [58]:
torch.numel(tensor3)

6

torch.*arrange(start, end, step = 1, dtype = None, ...)* returns the a tensor of size **(end - start) / step** with values from the interval between **[start, end]**.

In [66]:
torch.arange(1, 6)

tensor([1, 2, 3, 4, 5])

In [70]:
torch.arange(0, 4, 0.5, dtype = torch.double)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000],
       dtype=torch.float64)

### Convertions

To convert a PyTorch tensor to a NumPy array use the method tensor.*numpy()*

In [56]:
nparray = tensor3.numpy()
print(nparray)

[[-0.22877629  0.40546077 -0.74089503]
 [-0.14412118 -0.05739068  0.755485  ]]
